spring:
  application:
    name: HB Company Campaing Api
  jpa:
    database: h2
  datasource:
    name: H2 Platform
    url: jdbc:h2:mem:address_api;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password:

swagger:
  host: localhost:8080
  path: